/*
 * The one list of files the app is made of, bottom layer first, so every module loads after what it uses.
 * index.html, tests/index.html and scripts/build-single-file.sh all read this list.
 * Add a new file here, in its layer's block, or it will not load.
 */
window.BenchPanelLoadOrder = Object.freeze({
  styles: [
    'src/constants/theme.css',
    'src/main.css',
    'src/components/ModelTag/modelTag.css',
    'src/components/DataTable/dataTable.css',
    'src/components/Section/section.css',
    'src/components/StatTile/statTile.css',
    'src/components/EmptyState/emptyState.css',
    'src/components/SelectField/selectField.css',
    'src/components/LineChart/lineChart.css',
    'src/components/MetricTrendChart/metricTrendChart.css',
    'src/components/BarList/barList.css',
    'src/features/overview/overview.css',
    'src/features/comparison/comparison.css',
    'src/features/dataManager/dataManager.css',
    'src/navigation/appShell.css',
  ],

  scripts: [
    // types
    'src/types/result.js',
    'src/types/benchmarkRun.js',
    // constants and config
    'src/constants/metricCatalog.js',
    'src/constants/concurrencyNotes.js',
    'src/config/appConfig.js',
    // shared logic
    'src/utils/numberFormat.js',
    'src/utils/errorMessage.js',
    'src/utils/metricValues.js',
    'src/utils/runCollection.js',
    'src/utils/ranking.js',
    'src/utils/modelNaming.js',
    'src/utils/keyLevels.js',
    'src/utils/chartScale.js',
    'src/utils/csvBuilder.js',
    // services
    'src/services/resultParser.js',
    'src/services/resultFileService.js',
    'src/services/workspaceStorageService.js',
    'src/services/fileDownloadService.js',
    // store
    'src/store/workspaceStore.js',
    // shared UI
    'src/components/dom.js',
    'src/components/ModelTag/ModelTag.js',
    'src/components/DataTable/DataTable.js',
    'src/components/DataTable/metricColumn.js',
    'src/components/Section/Section.js',
    'src/components/StatTile/StatTile.js',
    'src/components/EmptyState/EmptyState.js',
    'src/components/SelectField/SelectField.js',
    'src/components/LineChart/chartTooltip.js',
    'src/components/LineChart/LineChart.js',
    'src/components/MetricTrendChart/MetricTrendChart.js',
    'src/components/BarList/BarList.js',
    // features
    'src/features/overview/highlights.js',
    'src/features/overview/scorecard.js',
    'src/features/overview/ScorecardTable.js',
    'src/features/overview/ModelOverviewTable.js',
    'src/features/overview/OverviewView.js',
    'src/features/overview/index.js',
    'src/features/comparison/levelLeaders.js',
    'src/features/comparison/MetricMatrixTable.js',
    'src/features/comparison/ConcurrencyRankingSection.js',
    'src/features/comparison/MetricTrendSection.js',
    'src/features/comparison/LatencySection.js',
    'src/features/comparison/ScalingSection.js',
    'src/features/comparison/gpuEfficiency.js',
    'src/features/comparison/GpuEfficiencySection.js',
    'src/features/comparison/ComparisonView.js',
    'src/features/comparison/index.js',
    'src/features/modelDetail/SummaryTable.js',
    'src/features/modelDetail/TokenSpeedTable.js',
    'src/features/modelDetail/LatencyPercentileTable.js',
    'src/features/modelDetail/RunDetailsTable.js',
    'src/features/modelDetail/ModelDetailView.js',
    'src/features/modelDetail/index.js',
    'src/features/dataManager/fileImportController.js',
    'src/features/dataManager/profileController.js',
    'src/features/dataManager/runsCsv.js',
    'src/features/dataManager/exportActions.js',
    'src/features/dataManager/FileDropZone.js',
    'src/features/dataManager/ImportNotice.js',
    'src/features/dataManager/ModelProfilesTable.js',
    'src/features/dataManager/LoadedRunsTable.js',
    'src/features/dataManager/DataManagerView.js',
    'src/features/dataManager/index.js',
    // navigation
    'src/navigation/tabRoutes.js',
    'src/navigation/appShell.js',
  ],

  entry: 'src/main.js',

  tests: [
    'tests/testRunner.js',
    'src/platform/moduleRegistry.test.js',
    'src/utils/metricValues.test.js',
    'src/utils/runCollection.test.js',
    'src/utils/ranking.test.js',
    'src/utils/numberFormat.test.js',
    'src/utils/modelNaming.test.js',
    'src/utils/chartScale.test.js',
    'src/utils/csvBuilder.test.js',
    'src/services/resultParser.test.js',
    'src/features/overview/scorecard.test.js',
    'tests/runTests.js',
  ],
});
